#!/bin/bash

# Copies a question directory and gives the new question a new UUID.

if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 {from_dir} {to_dir}" >&2
    exit 2
fi

if [[ ! -d "$1" ]]; then
    echo "Directory $1 does not exist. Exiting." >&2
    exit 2
fi

if [[ -e "$2" ]]; then
    echo "Directory $2 already exists. Exiting." >&2
    exit 2
fi

cp -r "$1" "$2"

uuid=`uuidgen`
uuidline=$(echo \ \ \  \"uuid\": \"$uuid\",)
sed -i "s/.*uuid.*/${uuidline}/" "$2/info.json"
